### ISSUE TITLE
Learning Snails

### ISSUE THREAD

**Issue by giveen** [kil0meters/snailplusplus#2]
Learning Snails either need to solve the puzzle faster or earn more per resolve. At this point there is no point purchasing a Learning Snail vs the lower tier Random Teleport as random teleport gives x3 the amount of earning and costs 1/10th of the Learning Snail

Learning Snail (w/ upgrade x 60)
![image](https://user-images.githubusercontent.com/1180939/222960615-01ee172d-d34f-4353-8ea9-bbee9bc26f69.png)
![image](https://user-images.githubusercontent.com/1180939/222960626-965924d7-2892-445d-81f3-2c727036d8f2.png)

vs

Random Teleport (w/ upgrade x60)
![image](https://user-images.githubusercontent.com/1180939/222960650-163c35d3-7967-452c-8057-d51569c6f68a.png)
![image](https://user-images.githubusercontent.com/1180939/222960658-40f8e1c2-ed0d-4e31-b0a2-6912892781ae.png)

**Comment by kil0meters** [comment]
You're definitely right about that. When I added the upgrades I didn't spend too much time balancing them, and it turns out the Random Teleport Snail with an Advanced Homing Beacon is significantly more powerful than a maxed Learning Snail. Although I'm not fully sure of the best way to improve the Learning Snail outside of just slightly buffing the upgrades I already have.
